use std::{env, path::Path};

fn main() {
    let target = env::var("TARGET").unwrap_or_default();

    // Map Rust target triples to the platform-specific binary directories.
    let (os, arch, ext) = match target.as_str() {
        "x86_64-unknown-linux-gnu" => ("linux", "x86_64", ""),
        "aarch64-unknown-linux-gnu" => ("linux", "aarch64", ""),
        "x86_64-apple-darwin" => ("macos", "x86_64", ""),
        "aarch64-apple-darwin" => ("macos", "aarch64", ""),
        "x86_64-pc-windows-msvc" => ("windows", "x86_64", ".exe"),
        "aarch64-pc-windows-msvc" => ("windows", "aarch64", ".exe"),
        _ => {
            println!(
                "cargo:warning=Unsupported target '{}'. Bundled MongoDB tools will not be available.",
                target
            );
            tauri_build::build();
            return;
        }
    };

    let platform_dir = format!("{}-{}", os, arch);

    // Verify the source binaries exist so the build fails early with a clear message.
    let dump_src = format!("binaries/{}/mongodump{}", platform_dir, ext);
    let restore_src = format!("binaries/{}/mongorestore{}", platform_dir, ext);
    for src in [&dump_src, &restore_src] {
        if !Path::new(src).exists() {
            panic!(
                "Bundled MongoDB tool not found for target {}: {}",
                target, src
            );
        }
    }

    // NOTE: The platform-specific Tauri config overlays (tauri.macos.conf.json,
    // tauri.windows.conf.json, tauri.linux.conf.json) are generated by the
    // GitHub Actions workflow before `tauri build` runs. The CLI must read
    // them before cargo build starts, so generating them here in build.rs is
    // too late.

    tauri_build::build();
}
