/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // Every colour the UI uses, by role. The values live in
      // src/themes/tokens.css as RGB channels so `<alpha-value>` works and
      // utilities like `bg-surface/50` resolve.
      colors: {
        'canvas': 'rgb(var(--td-canvas) / <alpha-value>)',
        'surface': 'rgb(var(--td-surface) / <alpha-value>)',
        'overlay': 'rgb(var(--td-overlay) / <alpha-value>)',
        'raised': 'rgb(var(--td-raised) / <alpha-value>)',
        'active': 'rgb(var(--td-active) / <alpha-value>)',
        'selected': 'rgb(var(--td-selected) / <alpha-value>)',
        'input': 'rgb(var(--td-input) / <alpha-value>)',
        'input-hover': 'rgb(var(--td-input-hover) / <alpha-value>)',
        'line': 'rgb(var(--td-line) / <alpha-value>)',
        'ink': 'rgb(var(--td-ink) / <alpha-value>)',
        'ink-2': 'rgb(var(--td-ink-2) / <alpha-value>)',
        'ink-3': 'rgb(var(--td-ink-3) / <alpha-value>)',
        'accent': 'rgb(var(--td-accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--td-accent-hover) / <alpha-value>)',
        'accent-solid': 'rgb(var(--td-accent-solid) / <alpha-value>)',
        'accent-solid-hover': 'rgb(var(--td-accent-solid-hover) / <alpha-value>)',
        'accent-soft': 'rgb(var(--td-accent-soft) / <alpha-value>)',
        'accent-soft-hover': 'rgb(var(--td-accent-soft-hover) / <alpha-value>)',
        'good': 'rgb(var(--td-good) / <alpha-value>)',
        'warn': 'rgb(var(--td-warn) / <alpha-value>)',
        'warn-soft': 'rgb(var(--td-warn-soft) / <alpha-value>)',
        'bad': 'rgb(var(--td-bad) / <alpha-value>)',
        'bad-hover': 'rgb(var(--td-bad-hover) / <alpha-value>)',
        'good-hover': 'rgb(var(--td-good-hover) / <alpha-value>)',
        'warn-bg': 'rgb(var(--td-warn-bg) / <alpha-value>)',
        'warn-line': 'rgb(var(--td-warn-line) / <alpha-value>)',
        'bad-bg': 'rgb(var(--td-bad-bg) / <alpha-value>)',
        'bad-line': 'rgb(var(--td-bad-line) / <alpha-value>)',
        'redis': 'rgb(var(--td-redis) / <alpha-value>)',
        'mongo': 'rgb(var(--td-mongo) / <alpha-value>)',
        'mongo-solid': 'rgb(var(--td-mongo-solid) / <alpha-value>)',
        'mongo-solid-hover': 'rgb(var(--td-mongo-solid-hover) / <alpha-value>)',
        'syn-blue': 'rgb(var(--td-syn-blue) / <alpha-value>)',
        'syn-cyan': 'rgb(var(--td-syn-cyan) / <alpha-value>)',
        'syn-yellow': 'rgb(var(--td-syn-yellow) / <alpha-value>)',
        'syn-teal': 'rgb(var(--td-syn-teal) / <alpha-value>)',
        'syn-purple': 'rgb(var(--td-syn-purple) / <alpha-value>)',
      },
    },
  },
  plugins: [],
}
