/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // Every colour the UI uses, by role. The values live in
      // src/themes/tokens.css as RGB channels so `<alpha-value>` works and
      // utilities like `bg-surface/50` resolve.
      fontSize: {
        // Backed by CSS vars so the whole scale tightens from one file.
        '2xs':  ['var(--td-text-2xs)',  { lineHeight: 'var(--td-lh-2xs)' }],
        'xs':   ['var(--td-text-xs)',   { lineHeight: 'var(--td-lh-xs)' }],
        'sm':   ['var(--td-text-sm)',   { lineHeight: 'var(--td-lh-sm)' }],
        'base': ['var(--td-text-base)', { lineHeight: 'var(--td-lh-base)' }],
        'lg':   ['var(--td-text-lg)',   { lineHeight: 'var(--td-lh-lg)' }],
      },
      fontFamily: {
        sans: 'var(--td-font-ui)',
        mono: 'var(--td-font-mono)',
      },
      colors: {
        'accent': 'rgb(var(--td-accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--td-accent-hover) / <alpha-value>)',
        'accent-soft': 'rgb(var(--td-accent-soft) / <alpha-value>)',
        'accent-soft-hover': 'rgb(var(--td-accent-soft-hover) / <alpha-value>)',
        'accent-solid': 'rgb(var(--td-accent-solid) / <alpha-value>)',
        'accent-solid-hover': 'rgb(var(--td-accent-solid-hover) / <alpha-value>)',
        'active': 'rgb(var(--td-active) / <alpha-value>)',
        'bad': 'rgb(var(--td-bad) / <alpha-value>)',
        'bad-bg': 'rgb(var(--td-bad-bg) / <alpha-value>)',
        'bad-hover': 'rgb(var(--td-bad-hover) / <alpha-value>)',
        'bad-line': 'rgb(var(--td-bad-line) / <alpha-value>)',
        'bad-solid': 'rgb(var(--td-bad-solid) / <alpha-value>)',
        'bad-solid-hover': 'rgb(var(--td-bad-solid-hover) / <alpha-value>)',
        'canvas': 'rgb(var(--td-canvas) / <alpha-value>)',
        'good': 'rgb(var(--td-good) / <alpha-value>)',
        'good-hover': 'rgb(var(--td-good-hover) / <alpha-value>)',
        'good-solid': 'rgb(var(--td-good-solid) / <alpha-value>)',
        'good-solid-hover': 'rgb(var(--td-good-solid-hover) / <alpha-value>)',
        'ink': 'rgb(var(--td-ink) / <alpha-value>)',
        'ink-2': 'rgb(var(--td-ink-2) / <alpha-value>)',
        'ink-3': 'rgb(var(--td-ink-3) / <alpha-value>)',
        'input': 'rgb(var(--td-input) / <alpha-value>)',
        'input-hover': 'rgb(var(--td-input-hover) / <alpha-value>)',
        'line': 'rgb(var(--td-line) / <alpha-value>)',
        'mongo': 'rgb(var(--td-mongo) / <alpha-value>)',
        'mongo-solid': 'rgb(var(--td-mongo-solid) / <alpha-value>)',
        'mongo-solid-hover': 'rgb(var(--td-mongo-solid-hover) / <alpha-value>)',
        'overlay': 'rgb(var(--td-overlay) / <alpha-value>)',
        'raised': 'rgb(var(--td-raised) / <alpha-value>)',
        'redis': 'rgb(var(--td-redis) / <alpha-value>)',
        'selected': 'rgb(var(--td-selected) / <alpha-value>)',
        'surface': 'rgb(var(--td-surface) / <alpha-value>)',
        'syn-blue': 'rgb(var(--td-syn-blue) / <alpha-value>)',
        'syn-cyan': 'rgb(var(--td-syn-cyan) / <alpha-value>)',
        'syn-purple': 'rgb(var(--td-syn-purple) / <alpha-value>)',
        'syn-teal': 'rgb(var(--td-syn-teal) / <alpha-value>)',
        'syn-yellow': 'rgb(var(--td-syn-yellow) / <alpha-value>)',
        'tag-1': 'rgb(var(--td-tag-1) / <alpha-value>)',
        'tag-2': 'rgb(var(--td-tag-2) / <alpha-value>)',
        'tag-3': 'rgb(var(--td-tag-3) / <alpha-value>)',
        'tag-4': 'rgb(var(--td-tag-4) / <alpha-value>)',
        'tag-5': 'rgb(var(--td-tag-5) / <alpha-value>)',
        'tag-6': 'rgb(var(--td-tag-6) / <alpha-value>)',
        'tag-7': 'rgb(var(--td-tag-7) / <alpha-value>)',
        'tag-8': 'rgb(var(--td-tag-8) / <alpha-value>)',
        'warn': 'rgb(var(--td-warn) / <alpha-value>)',
        'warn-bg': 'rgb(var(--td-warn-bg) / <alpha-value>)',
        'warn-line': 'rgb(var(--td-warn-line) / <alpha-value>)',
        'warn-soft': 'rgb(var(--td-warn-soft) / <alpha-value>)',
        'warn-solid': 'rgb(var(--td-warn-solid) / <alpha-value>)',
        'warn-solid-hover': 'rgb(var(--td-warn-solid-hover) / <alpha-value>)',
      },
    },
  },
  plugins: [],
}
